name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Каждые 10 минут
  workflow_dispatch:        # Для ручного запуска

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render server
        run: |
          curl -s -o /dev/null -w "HTTP status: %{http_code}\n" \
          -X GET https://telegram-analytics-t6pf.onrender.com/health 
